Classwork53/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogue import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('movies/', views.Movieslist.as_view(), name='allmovies'),
    path('actors/', views.Actorslist.as_view(), name='allactors'),
    path('director/', views.Directorslist.as_view(), name='alldirectors'),
    # path('info/<int:id>/', views.movieinfo, name='movieinfo'),
    path('movie_info/<slug:pk>/<str:title>', views.Moviedetails.as_view(), name='movieinfo'),
    path('actor_info/<slug:pk>/<str:last_name>', views.Actordetails.as_view(), name='actorinfo'),
    path('director_info/<slug:pk>/<str:last_name>', views.Directordetails.as_view(), name='directorinfo'),
    path('user/', include('django.contrib.auth.urls')),
    path('subscr/', views.subscr, name='subscr'),
    path('subscr/watcher/<int:id1>/<int:id2>/<int:id3>', views.watcher, name='watcher'),
    path('subscr/buy/<int:type>', views.buy, name='buysub'),
    path('user/registration/', views.registration, name='registration'),
    path('submanager/', views.submanager, name='submanager'),
    path('switch_to_bronze/', views.switch_to_bronze, name='switch_to_bronze'),
    path('switch_to_silver/', views.switch_to_silver, name='switch_to_silver'),
    path('switch_to_gold/', views.switch_to_gold, name='switch_to_gold'),
    path('search/', views.search, name='search'),
]





'''
reset_form
reset_done
reset_confirm
reset_complete
'''

catalogue/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Genre(models.Model):
    genre_name = models.CharField(max_length=100, verbose_name='Genre:')

    def __str__(self):
        return self.genre_name


class Director(models.Model):
    director_first_name = models.CharField(max_length=100, verbose_name='Director first name:')
    director_last_name = models.CharField(max_length=100, verbose_name='Director last name:')

    def __str__(self):
        # return f'{self.director_last_name}, {self.director_first_name}'
        return f'{self.director_first_name} {self.director_last_name}'

    def get_absolute_url(self):
        return reverse('directorinfo', args=[self.id, self.director_last_name])


class Actor(models.Model):
    actor_first_name = models.CharField(max_length=100, verbose_name='Actor first name:')
    actor_last_name = models.CharField(max_length=100, verbose_name='Actor last name:')
    actor_birth_date = models.DateField(null=True, blank=True, verbose_name='Date of birth:')
    actor_country = models.CharField(max_length=100, verbose_name='Born in:', null=True, blank=True)

    def __str__(self):
        return self.actor_last_name

    def get_absolute_url(self):
        return reverse('actorinfo', args=[self.id, self.actor_last_name])


class Subscription(models.Model):
    subs_selection = (('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD'))
    subscription_type = models.CharField(max_length=100, choices=subs_selection, verbose_name='Subscription type:')

    def __str__(self):
        return self.subscription_type



class AgeRestriction(models.Model):
    choice = (('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'))
    age_restr = models.CharField(max_length=20, choices=choice, verbose_name='Age restriction:')

    def __str__(self):
        return self.age_restr


class Country(models.Model):

    movie_country = models.CharField(max_length=100, verbose_name='Production country:')

    def __str__(self):
        return self.movie_country


class Movie(models.Model):
    title = models.CharField(max_length=100, verbose_name='Movie title:')
    genre = models.ForeignKey(to=Genre, on_delete=models.SET_DEFAULT, default=1)
    rating = models.FloatField(verbose_name='Critics score:')
    country = models.ForeignKey(to=Country, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(to=Director, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=9999, verbose_name='Movie synopsis:')
    year = models.IntegerField(verbose_name='Production year(s):')
    age_rate = models.ForeignKey(to=AgeRestriction, on_delete=models.SET_NULL, null=True)
    actors = models.ManyToManyField(to=Actor, verbose_name='Actors list:')
    subscription = models.ForeignKey(to=Subscription, on_delete=models.SET_NULL, null=True)
    movie_poster = models.CharField(max_length=255, blank=True, null=True, verbose_name='Movie poster:')

    def __str__(self):
        return self.title

    def display_actors(self):
        tempstr = ''
        for a in self.actors.all():
            tempstr += a.actor_last_name + ' '
        return tempstr
    display_actors.short_description = 'Actor(s)'       # замена названия столбца на сайте

    def get_absolute_url(self):
        return reverse('movieinfo', args=[self.id, self.title])

templates/buy.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <h2>You are now {{ subscription }} subscriber!</h2>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'catalogue/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/1.css' %}">
    {% block head %}
        <title>Catalogue</title>
    {% endblock head %}
</head>
<body>
{#    <a href="/admin/">ADMIN</a>#}
{#    <h2>Movies catalogue</h2>#}
    <h2>Welcome, {{ username }}</h2>

    {% block menu %}
        <div class="menu">
            <a href="{% url 'allmovies' %}">Movies</a>
            <a href="{% url 'allactors' %}">Actors</a>
            <a href="{% url 'alldirectors' %}">Directors</a>
            <a href="{% url 'subscr' %}">Movies catalogue</a>
            <a href="{% url 'search' %}">Movies search</a>
            <a href="{% url 'home' %}">GLAGNE</a>
            {% if user.username %}
                <a href="{% url 'submanager' %}">Submanager</a>
            {% endif %}
            {% if not user.username %}
                <a href="{% url 'login' %}">Login</a>
            {% else %}
                <a href="{% url 'logout' %}">Logout</a>
            {% endif %}
        </div>
    {% endblock menu %}

    {% block content %}
        <h2>There are {{ x }} movies in the DB</h2>
        <h2>There are {{ xx }} actors in the DB</h2>
        <h2>There are {{ xxx }} directors in the DB</h2>
        <h2>There are {{ xxxx }} bronze tier movies in the DB</h2>
    {% endblock content %}

    {# Код для блока с навигацией по страницам, если выводится определённое кол-во фильмов (кол-во указано во views  "paginate_by = X")      #}
    {% if is_paginated %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
    {% endif %}


</body>
</html>

templates/search.html
{% extends 'index.html' %}
{% load static %}

{% block head %}
    <title>search</title>
    <link rel="stylesheet" href="{% static 'css/subscr.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock head %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="search-form">{{ search }}</div>
        <input type="submit" value="Search!" class="search-button">
    </form>

    {% if found_movie|length != 0 %}
        {% for j in found_movie %}
            <div class="card">
                <img src="{% static j.movie_poster %}" alt="poster">
                <p class="title">{{ j.title }}</p>
                <p class="year">{{ j.year }}</p>
                <p class="director">{{ j.director }}</p>
            </div>
        {% endfor %}
    {% elif found_movie == 0 %}
        <h2 class="card">Found nothing</h2>
    {% endif %}
{% endblock content %}

templates/submanager.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/submanager.css' %}">
    {% if user_sub_type == 3 %}
        <link rel="stylesheet" href="{% static 'css/gold.css' %}">
    {% elif user_sub_type == 2 %}
        <link rel="stylesheet" href="{% static 'css/silver.css' %}">
    {% elif user_sub_type == 1 %}
        <link rel="stylesheet" href="{% static 'css/bronze.css' %}">
    {% endif %}
{% endblock head %}


{##}
{#{% block content %}#}
{#    <h2>Your current sub tier is {{ subtier }}.</h2>#}
{#    <h3>Would you like to switch tier subscription?</h3>#}
{#    {% if user_sub_type == 3 %}#}
{#        <button>Bronze</button>#}
{#        <button>Silver</button>#}
{#        <button>Gold</button>#}
{#    {% elif user_sub_type == 2 %}#}
{#        <button>Bronze</button>#}
{#        <button>Silver</button>#}
{#        <button>Gold</button>#}
{#    {% elif user_sub_type == 1 %}#}
{#        <button>Bronze</button>#}
{#        <button>Silver</button>#}
{#        <button>Gold</button>#}
{#    {% endif %}#}
{##}
{#{% endblock content %}#}

{% block content %}
    <h2>Your current subscription is <span class="current-sub">{{ subtier }}</span></h2>
    <h3>Would you like to switch tier subscription?</h3>

    {% if user_sub_type == 3 %}
        <form method="POST" action="{% url 'switch_to_bronze' %}">
          {% csrf_token %}
          <button type="submit" style="color: #cd7f32; background-color: #2c2828">Bronze</button>
        </form>
        <form method="POST" action="{% url 'switch_to_silver' %}">
          {% csrf_token %}
          <button type="submit" style="color: silver; background-color: #2c2828">Silver</button>
        </form>

    {% elif user_sub_type == 2 %}
        <form method="POST" action="{% url 'switch_to_bronze' %}">
          {% csrf_token %}
          <button type="submit" style="color: #cd7f32; background-color: #2c2828">Bronze</button>
        </form>
        <form method="POST" action="{% url 'switch_to_gold' %}">
          {% csrf_token %}
            <button type="submit" style="color: gold; background-color: #2c2828">Gold</button>
        </form>

    {% elif user_sub_type == 1 %}
        <form method="POST" action="{% url 'switch_to_silver' %}">
          {% csrf_token %}
          <button type="submit" style="color: silver; background-color: #2c2828">Silver</button>
        </form>
        <form method="POST" action="{% url 'switch_to_gold' %}">
          {% csrf_token %}
            <button type="submit" style="color: gold; background-color: #2c2828">Gold</button>
        </form>
    {% endif %}
{% endblock content %}

templates/subscription.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Catalogue</title>
    <link rel="stylesheet" href="{% static 'css/subscr.css' %}">
{% endblock head %}

{% block content %}
    {% for i in subscriptions %}
        <h3 class="main">{{ i.subscription_type }}</h3>
        <div class="cont">
        {% for j in i.movie_set.all %}
            <div class="card">
                <img src="{% static j.movie_poster %}" alt="poster">
                <p class="title">{{ j.title }}</p>
                <p class="year">{{ j.year }}</p>
                <p class="director">{{ j.director }}</p>

                {% if not user.username %}
                <a href="{% url 'watcher' j.id i.id 0 %}">
                    <button class="watch-btn">WATCH!</button>
                </a>
                {% else %}
                <a href="{% url 'watcher' j.id i.id user.id %}">
                    <button class="watch-btn">WATCH!</button>
                </a>
                {% endif %}

                <br>
            </div>

            {% endfor %}
        </div>
    {% endfor %}

{% endblock content %}

templates/watch.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Watch here</title>
    <link rel="stylesheet" href="{% static 'css/watch.css' %}">
{% endblock head %}

{% block content %}
    <h2>Movie {{ movie }}</h2>
    <div class="screen">
        {% if permission %}
            <h3>Enjoy your movie!</h3>
        {% else %}
            <h3>Your subscription type is not enough</h3>
        {% endif %}
    </div>
    <h3>Your subscription {{ subscriptiontier }}</h3>
    <h3>Movie subscription {{ subscriptionmovie }}</h3>
    {% if not permission %}
        {% if user.username %}
            <h4>
                <a href="{% url 'buysub' type=2 %}">Buy Silver Tier.</a>
            </h4>

            <h4>
                <a href="{% url 'buysub' type=3 %}">Buy Gold Tier.</a>
            </h4>
        {% else %}
            <h4>
                <a href="{% url 'login' %}">Buy Silver Tier.</a>
            </h4>

            <h4>
                <a href="{% url 'login' %}">Buy Gold Tier.</a>
            </h4>
        {% endif %}
    {% endif %}

{% endblock content %}